apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: vote-app
spec:
  selector:
    app: db
  type: ClusterIP

  ports:
  - name: db-port
    protocol: TCP
    port: 5432
    targetPort: 5432
