apiVersion: v1
kind: Service
metadata:
  name: vote-service
  namespace: vote-app
spec:
  selector:
    app: vote
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: vote
    protocol: TCP
    port: 5000
    targetPort: 5000
    