apiVersion: apps/v1
kind: Deployment
metadata:
  name:  vote
  namespace: vote-app
  labels:
    app:  vote
spec:
  selector:
    matchLabels:
      app: vote
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  vote
    spec:
      containers:
      - name:  vote
        image:  marufhossainbd615/vote:latest                
        