apiVersion: apps/v1
kind: Deployment
metadata:
  name:  worker
  namespace: vote-app
  labels:
    app:  worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  worker
    spec:
      containers:
      - name:  worker
        image:  marufhossainbd615/worker:latest                
        